package contextgraph

import (
	"context"
	"time"

	"github.com/KDZZZZZZ/threadmill-AgentTeams/internal/kernel"
)

type NodeKind string

const (
	NodeKindDirective  NodeKind = "directive"
	NodeKindFact       NodeKind = "fact"
	NodeKindHypothesis NodeKind = "hypothesis"
)

type NodeStatus string

const (
	NodeStatusAccepted   NodeStatus = "accepted"
	NodeStatusDisputed   NodeStatus = "disputed"
	NodeStatusSuperseded NodeStatus = "superseded"
	NodeStatusOutdated   NodeStatus = "outdated"
)

type SubgraphKind string

const (
	SubgraphKindGeneral SubgraphKind = "general"
	SubgraphKindTask    SubgraphKind = "task"
)

type EdgeKind string

const (
	EdgeKindLogicalAdjacent     EdgeKind = "logical_adjacent"
	EdgeKindDerivesFromSubgraph EdgeKind = "derives_from_subgraph"
)

// ContextNode is the exact authority-field set from docs/context-graph.md.
// Persistence metadata such as project, revision, timestamps, and audit lives
// in store records, not in this object.
type ContextNode struct {
	ID             string   `json:"id"`
	Kind           string   `json:"kind"`
	Statement      string   `json:"statement"`
	Status         string   `json:"status"`
	SubgraphIDs    []string `json:"subgraph_ids"`
	SourceRefs     []string `json:"source_refs"`
	CreatorAgentID string   `json:"creator_agent_id"`
}

// NodeCreationContext is generated by Context Service. Agents never provide or
// mutate it directly.
type NodeCreationContext struct {
	CreatorAgentID        string   `json:"creator_agent_id"`
	PreviousNodeID        string   `json:"previous_node_id"`
	SubscribedSubgraphIDs []string `json:"subscribed_subgraph_ids"`
}

type MemoryCandidate struct {
	Statement   string   `json:"statement"`
	Kind        string   `json:"kind"`
	SourceRefs  []string `json:"source_refs"`
	SubgraphIDs []string `json:"subgraph_ids"`
}

type CandidateBufferRecord struct {
	CandidateID           string
	TaskID                string
	Candidate             MemoryCandidate
	CreationContext       NodeCreationContext
	CreatedByInvocationID kernel.InvocationID
	CreatedAt             time.Time
}

type ContextEdge struct {
	FromRef  string `json:"from_ref"`
	ToNodeID string `json:"to_node_id"`
	Kind     string `json:"kind"`
}

type ContextGraphSnapshot struct {
	ProjectID kernel.ProjectID          `json:"project_id"`
	Revision  kernel.Revision           `json:"revision"`
	Nodes     []ContextSnapshotNode     `json:"nodes"`
	Edges     []ContextSnapshotEdge     `json:"edges"`
	Subgraphs []ContextSnapshotSubgraph `json:"subgraphs"`
}

type ContextSnapshotNode struct {
	NodeID      string     `json:"node_id"`
	Kind        string     `json:"kind"`
	Statement   string     `json:"statement"`
	Status      string     `json:"status"`
	SourceRefs  []string   `json:"source_refs"`
	SubgraphIDs []string   `json:"subgraph_ids"`
	UsageCount  int        `json:"usage_count"`
	LastUsedAt  *time.Time `json:"last_used_at"`
}

type ContextSnapshotEdge struct {
	FromRef  string `json:"from_ref"`
	ToNodeID string `json:"to_node_id"`
	Kind     string `json:"kind"`
}

type ContextSnapshotSubgraph struct {
	SubgraphID string        `json:"subgraph_id"`
	Name       string        `json:"name"`
	Summary    string        `json:"summary"`
	Revision   int64         `json:"revision"`
	Kind       string        `json:"kind"`
	TaskID     kernel.TaskID `json:"task_id,omitempty"`
}

type ContextSubgraph struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Summary  string `json:"summary"`
	Revision int64  `json:"revision"`
	Kind     string `json:"kind"`
}

type NodeRecord struct {
	Node      ContextNode
	Revision  kernel.Revision
	ProjectID kernel.ProjectID
	CreatedAt time.Time
	Sequence  uint64
}

type SubgraphRecord struct {
	Subgraph  ContextSubgraph
	ProjectID kernel.ProjectID
	TaskID    kernel.TaskID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AuditEvent struct {
	ID        string
	ProjectID kernel.ProjectID
	ActorID   kernel.ActorPrincipalID
	Action    string
	SubjectID string
	CreatedAt time.Time
}

type OutboxEvent struct {
	ID        string
	Topic     string
	Key       string
	Payload   []byte
	CreatedAt time.Time
}

type CreateNodeInput struct {
	Node            ContextNode
	CreationContext NodeCreationContext
}

type CreateNodesRequest struct {
	ExpectedGraphRevision kernel.Revision
	Nodes                 []CreateNodeInput
}

type CreateNodesResult struct {
	GraphRevision kernel.Revision
	Nodes         []ContextNode
	Edges         []ContextEdge
	AuditEvents   []AuditEvent
	OutboxEvents  []OutboxEvent
}

type ListSubgraphsRequest struct {
	Filter string `json:"filter"`
}

type ExploreRequest struct {
	AnchorRef string `json:"anchor_ref"`
	Depth     int    `json:"depth"`
}

type ContextSliceDelta struct {
	Nodes         []ContextNode `json:"nodes"`
	Frontier      []string      `json:"frontier"`
	GraphRevision int64         `json:"graph_revision"`
}

type SearchRequest struct {
	Keywords   []string `json:"keywords"`
	Scope      []string `json:"scope"`
	AnchorRefs []string `json:"anchor_refs"`
}

type ContextSearchResult struct {
	Slice           ContextSliceDelta `json:"slice"`
	MatchedKeywords []string          `json:"matched_keywords"`
	SubscriptionIDs []string          `json:"subscription_ids"`
}

type SubscribeRequest struct {
	SubgraphIDs []string `json:"subgraph_ids"`
	EventKinds  []string `json:"event_kinds"`
}

type ContextSubscription struct {
	ID                   string   `json:"id"`
	ConsumerInvocationID string   `json:"consumer_invocation_id"`
	SubgraphIDs          []string `json:"subgraph_ids"`
	EventKinds           []string `json:"event_kinds"`
	PermissionSnapshot   string   `json:"permission_snapshot"`
}

type ContextSubscriptionRecord struct {
	Subscription ContextSubscription
	ProjectID    kernel.ProjectID
	TaskID       kernel.TaskID
	Role         string
	Source       string
	Active       bool
	CanceledAt   *time.Time
	ExpiredAt    *time.Time
	CreatedAt    time.Time
}

type ContextDelta struct {
	ID             string   `json:"id"`
	ProjectID      string   `json:"project_id"`
	SubscriptionID string   `json:"subscription_id"`
	InvocationID   string   `json:"invocation_id"`
	EventID        string   `json:"event_id"`
	EventKind      string   `json:"event_kind"`
	SubgraphIDs    []string `json:"subgraph_ids"`
	GraphRevision  int64    `json:"graph_revision"`
}

type ContextSlice struct {
	Nodes           []ContextNode `json:"nodes"`
	SubscriptionIDs []string      `json:"subscription_ids"`
	GraphRevision   int64         `json:"graph_revision"`
}

type invocationScopeKey struct {
	ProjectID    kernel.ProjectID
	InvocationID kernel.InvocationID
}

type SubscriptionInspection struct {
	ID                   string   `json:"id"`
	ConsumerInvocationID string   `json:"consumer_invocation_id"`
	Source               string   `json:"source"`
	SubgraphIDs          []string `json:"subgraph_ids"`
	EventKinds           []string `json:"event_kinds"`
	Active               bool     `json:"active"`
}

type ContextNodeRef = string

type PhaseEndpointRef struct {
	TaskID     kernel.TaskID     `json:"task_id"`
	EndpointID kernel.EndpointID `json:"endpoint_id"`
}

type TaskContextSubgraphBinding struct {
	TaskID     string `json:"task_id"`
	SubgraphID string `json:"subgraph_id"`
}

type TaskContextRecipient struct {
	TaskID       string             `json:"task_id"`
	EndpointRefs []PhaseEndpointRef `json:"endpoint_refs"`
}

type TaskContextProjection struct {
	ProjectionID   string                 `json:"projection_id"`
	SourceRevision string                 `json:"source_revision"`
	Statement      string                 `json:"statement"`
	Kind           string                 `json:"kind"`
	SourceRefs     []string               `json:"source_refs"`
	SubgraphIDs    []string               `json:"subgraph_ids"`
	Recipients     []TaskContextRecipient `json:"recipients"`
}

type ProjectTaskContextRequest struct {
	Projection TaskContextProjection `json:"projection"`
}

type TaskMemoryCandidateView struct {
	CandidateID string          `json:"candidate_id"`
	Candidate   MemoryCandidate `json:"candidate"`
}

type TaskMemoryBufferView struct {
	Candidates []TaskMemoryCandidateView `json:"candidates"`
}

type SubmitCandidateRequest struct {
	Candidate MemoryCandidate `json:"candidate"`
}

type FrozenCandidateBatch struct {
	TaskID     string                    `json:"task_id"`
	Candidates []TaskMemoryCandidateView `json:"candidates"`
}

type CandidateReviewDecision struct {
	CandidateID  string   `json:"candidate_id"`
	Action       string   `json:"action"`
	Statement    string   `json:"statement"`
	Kind         string   `json:"kind"`
	SubgraphIDs  []string `json:"subgraph_ids"`
	TargetNodeID string   `json:"target_node_id"`
	Reason       string   `json:"reason"`
}

type CandidateReviewSubmission struct {
	Decisions []CandidateReviewDecision `json:"decisions"`
}

type TaskMemoryReviewReceipt struct {
	TaskID      string   `json:"task_id"`
	ReviewedIDs []string `json:"reviewed_ids"`
	NodeIDs     []string `json:"node_ids"`
	RejectedIDs []string `json:"rejected_ids"`
}

type TaskMemoryReviewState string

const (
	TaskMemoryOpen             TaskMemoryReviewState = "open"
	TaskMemoryFrozenUnreviewed TaskMemoryReviewState = "frozen-unreviewed"
	TaskMemoryReviewed         TaskMemoryReviewState = "reviewed"
)

type taskScopeKey struct {
	ProjectID kernel.ProjectID
	TaskID    kernel.TaskID
}

type projectionScopeKey struct {
	ProjectID    kernel.ProjectID
	ProjectionID string
}

type TaskEndpointResolver interface {
	TaskExists(ctx context.Context, projectID kernel.ProjectID, taskID kernel.TaskID) (bool, error)
	TaskDone(ctx context.Context, projectID kernel.ProjectID, taskID kernel.TaskID) (bool, error)
	EndpointExists(ctx context.Context, projectID kernel.ProjectID, endpoint PhaseEndpointRef) (bool, error)
}

type GetSubgraphRequest struct {
	SubgraphID string `json:"subgraph_id"`
}

type GetNodeRequest struct {
	NodeID string `json:"node_id"`
}

type CreateGeneralNodeRequest struct {
	Statement   string   `json:"statement"`
	Kind        string   `json:"kind"`
	SourceRefs  []string `json:"source_refs"`
	SubgraphIDs []string `json:"subgraph_ids"`
}

type UpdateGeneralNodeRequest struct {
	NodeID         string   `json:"node_id"`
	SourceRevision string   `json:"source_revision"`
	Statement      string   `json:"statement"`
	Kind           string   `json:"kind"`
	SourceRefs     []string `json:"source_refs"`
	SubgraphIDs    []string `json:"subgraph_ids"`
	Status         string   `json:"status"`
}

type DeleteGeneralNodeRequest struct {
	NodeID         string `json:"node_id"`
	SourceRevision string `json:"source_revision"`
	Reason         string `json:"reason"`
}

type CreateGeneralSubgraphRequest struct {
	Name    string   `json:"name"`
	Summary string   `json:"summary"`
	NodeIDs []string `json:"node_ids"`
}

type UpdateGeneralSubgraphRequest struct {
	SubgraphID string   `json:"subgraph_id"`
	Revision   int64    `json:"revision"`
	Name       string   `json:"name"`
	Summary    string   `json:"summary"`
	NodeIDs    []string `json:"node_ids"`
}

type DeleteGeneralSubgraphRequest struct {
	SubgraphID string `json:"subgraph_id"`
	Revision   int64  `json:"revision"`
	Reason     string `json:"reason"`
}
