package contextgraph

import (
	"time"

	"github.com/KDZZZZZZ/threadmill-AgentTeams/internal/kernel"
)

type NodeKind string

const (
	NodeKindDirective  NodeKind = "directive"
	NodeKindFact       NodeKind = "fact"
	NodeKindHypothesis NodeKind = "hypothesis"
)

type NodeStatus string

const (
	NodeStatusAccepted   NodeStatus = "accepted"
	NodeStatusDisputed   NodeStatus = "disputed"
	NodeStatusSuperseded NodeStatus = "superseded"
	NodeStatusOutdated   NodeStatus = "outdated"
)

type SubgraphKind string

const (
	SubgraphKindGeneral SubgraphKind = "general"
	SubgraphKindTask    SubgraphKind = "task"
)

type EdgeKind string

const (
	EdgeKindLogicalAdjacent     EdgeKind = "logical_adjacent"
	EdgeKindDerivesFromSubgraph EdgeKind = "derives_from_subgraph"
)

// ContextNode is the exact authority-field set from docs/context-graph.md.
// Persistence metadata such as project, revision, timestamps, and audit lives
// in store records, not in this object.
type ContextNode struct {
	ID             string   `json:"id"`
	Kind           string   `json:"kind"`
	Statement      string   `json:"statement"`
	Status         string   `json:"status"`
	SubgraphIDs    []string `json:"subgraph_ids"`
	SourceRefs     []string `json:"source_refs"`
	CreatorAgentID string   `json:"creator_agent_id"`
}

// NodeCreationContext is generated by Context Service. Agents never provide or
// mutate it directly.
type NodeCreationContext struct {
	CreatorAgentID        string   `json:"creator_agent_id"`
	PreviousNodeID        string   `json:"previous_node_id"`
	SubscribedSubgraphIDs []string `json:"subscribed_subgraph_ids"`
}

type MemoryCandidate struct {
	Statement   string   `json:"statement"`
	Kind        string   `json:"kind"`
	SourceRefs  []string `json:"source_refs"`
	SubgraphIDs []string `json:"subgraph_ids"`
}

type CandidateBufferRecord struct {
	CandidateID     string
	TaskID          string
	Candidate       MemoryCandidate
	CreationContext NodeCreationContext
}

type ContextEdge struct {
	FromRef  string `json:"from_ref"`
	ToNodeID string `json:"to_node_id"`
	Kind     string `json:"kind"`
}

type ContextSubgraph struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Summary  string `json:"summary"`
	Revision int64  `json:"revision"`
	Kind     string `json:"kind"`
}

type NodeRecord struct {
	Node      ContextNode
	Revision  kernel.Revision
	ProjectID kernel.ProjectID
	CreatedAt time.Time
	Sequence  uint64
}

type SubgraphRecord struct {
	Subgraph  ContextSubgraph
	ProjectID kernel.ProjectID
	TaskID    kernel.TaskID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AuditEvent struct {
	ID        string
	ProjectID kernel.ProjectID
	ActorID   kernel.ActorPrincipalID
	Action    string
	SubjectID string
	CreatedAt time.Time
}

type OutboxEvent struct {
	ID        string
	Topic     string
	Key       string
	Payload   []byte
	CreatedAt time.Time
}

type CreateNodeInput struct {
	Node            ContextNode
	CreationContext NodeCreationContext
}

type CreateNodesRequest struct {
	ExpectedGraphRevision kernel.Revision
	Nodes                 []CreateNodeInput
}

type CreateNodesResult struct {
	GraphRevision kernel.Revision
	Nodes         []ContextNode
	Edges         []ContextEdge
	AuditEvents   []AuditEvent
	OutboxEvents  []OutboxEvent
}

type ListSubgraphsRequest struct {
	Filter string `json:"filter"`
}

type ExploreRequest struct {
	AnchorRef string `json:"anchor_ref"`
	Depth     int    `json:"depth"`
}

type ContextSliceDelta struct {
	Nodes         []ContextNode `json:"nodes"`
	Frontier      []string      `json:"frontier"`
	GraphRevision int64         `json:"graph_revision"`
}

type SearchRequest struct {
	Keywords   []string `json:"keywords"`
	Scope      []string `json:"scope"`
	AnchorRefs []string `json:"anchor_refs"`
}

type ContextSearchResult struct {
	Slice           ContextSliceDelta `json:"slice"`
	MatchedKeywords []string          `json:"matched_keywords"`
	SubscriptionIDs []string          `json:"subscription_ids"`
}

type ContextNodeRef = string

type GetSubgraphRequest struct {
	SubgraphID string `json:"subgraph_id"`
}

type GetNodeRequest struct {
	NodeID string `json:"node_id"`
}

type CreateGeneralNodeRequest struct {
	Statement   string   `json:"statement"`
	Kind        string   `json:"kind"`
	SourceRefs  []string `json:"source_refs"`
	SubgraphIDs []string `json:"subgraph_ids"`
}

type UpdateGeneralNodeRequest struct {
	NodeID         string   `json:"node_id"`
	SourceRevision string   `json:"source_revision"`
	Statement      string   `json:"statement"`
	Kind           string   `json:"kind"`
	SourceRefs     []string `json:"source_refs"`
	SubgraphIDs    []string `json:"subgraph_ids"`
	Status         string   `json:"status"`
}

type DeleteGeneralNodeRequest struct {
	NodeID         string `json:"node_id"`
	SourceRevision string `json:"source_revision"`
	Reason         string `json:"reason"`
}

type CreateGeneralSubgraphRequest struct {
	Name    string   `json:"name"`
	Summary string   `json:"summary"`
	NodeIDs []string `json:"node_ids"`
}

type UpdateGeneralSubgraphRequest struct {
	SubgraphID string   `json:"subgraph_id"`
	Revision   int64    `json:"revision"`
	Name       string   `json:"name"`
	Summary    string   `json:"summary"`
	NodeIDs    []string `json:"node_ids"`
}

type DeleteGeneralSubgraphRequest struct {
	SubgraphID string `json:"subgraph_id"`
	Revision   int64  `json:"revision"`
	Reason     string `json:"reason"`
}
